// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjH6Qk00AtkDIuFAwjmOdxsSj7vGVzQR0',
    appId: '1:288232036542:web:d7cc8157516c3be5f326ef',
    messagingSenderId: '288232036542',
    projectId: 'instiapp-db011',
    authDomain: 'instiapp-db011.firebaseapp.com',
    storageBucket: 'instiapp-db011.firebasestorage.app',
    measurementId: 'G-SLJLWFJC4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRXvbQQmIPlAbIEWKeke2aXxWBIPOKN2o',
    appId: '1:288232036542:android:2be20377f10dab1df326ef',
    messagingSenderId: '288232036542',
    projectId: 'instiapp-db011',
    storageBucket: 'instiapp-db011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAFnGJpb2DpKa0uXgWxsYxMK37J3WYrTE',
    appId: '1:288232036542:ios:2100964481ee47dff326ef',
    messagingSenderId: '288232036542',
    projectId: 'instiapp-db011',
    storageBucket: 'instiapp-db011.firebasestorage.app',
    iosBundleId: 'com.example.campusHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAFnGJpb2DpKa0uXgWxsYxMK37J3WYrTE',
    appId: '1:288232036542:ios:2100964481ee47dff326ef',
    messagingSenderId: '288232036542',
    projectId: 'instiapp-db011',
    storageBucket: 'instiapp-db011.firebasestorage.app',
    iosBundleId: 'com.example.campusHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjH6Qk00AtkDIuFAwjmOdxsSj7vGVzQR0',
    appId: '1:288232036542:web:bf15b6b8b201b9c2f326ef',
    messagingSenderId: '288232036542',
    projectId: 'instiapp-db011',
    authDomain: 'instiapp-db011.firebaseapp.com',
    storageBucket: 'instiapp-db011.firebasestorage.app',
    measurementId: 'G-CBZRZ9PZXB',
  );

}